// <copyright file="Emitter.cs" company="Canon Europe Limited">
// Copyright (c) Canon Europe Limited. All rights reserved.
// </copyright>

namespace AutoGuard;

internal static class Emitter
{
    public const string AttributeSource =
        """
        // <auto-generated by Swevo.AutoGuard/>
        #nullable enable
        namespace AutoGuard;

        /// <summary>Marks a partial class for generated constructor guard validation.</summary>
        [System.AttributeUsage(System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        public sealed class AutoGuardAttribute : System.Attribute { }

        /// <summary>Requires a constructor argument to be non-null.</summary>
        [System.AttributeUsage(System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
        public sealed class NotNullAttribute : System.Attribute { }

        /// <summary>Requires a constructor argument to be non-empty.</summary>
        [System.AttributeUsage(System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
        public sealed class NotEmptyAttribute : System.Attribute { }

        /// <summary>Requires a constructor argument to be within an inclusive range.</summary>
        [System.AttributeUsage(System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
        public sealed class InRangeAttribute(double min, double max) : System.Attribute
        {
            /// <summary>Gets the inclusive minimum value.</summary>
            public double Min { get; } = min;

            /// <summary>Gets the inclusive maximum value.</summary>
            public double Max { get; } = max;
        }

        /// <summary>Requires a constructor argument to match a regular expression.</summary>
        [System.AttributeUsage(System.AttributeTargets.Parameter, Inherited = false, AllowMultiple = false)]
        public sealed class MatchesAttribute(string pattern) : System.Attribute
        {
            /// <summary>Gets the regular expression pattern.</summary>
            public string Pattern { get; } = pattern;
        }
        """;

    public const string ValidatorSource =
        """
        // <auto-generated by Swevo.AutoGuard/>
        #nullable enable
        namespace AutoGuard;

        /// <summary>Generated validation helpers used by <see cref="AutoGuardAttribute"/> types.</summary>
        internal static class AutoGuardValidator
        {
            internal static bool NotNull(object? value, string name)
            {
                if (value is null)
                {
                    throw new System.ArgumentNullException(name);
                }

                return true;
            }

            internal static bool NotEmpty(string? value, string name)
            {
                if (string.IsNullOrWhiteSpace(value))
                {
                    throw new System.ArgumentException("Value cannot be null, empty, or whitespace.", name);
                }

                return true;
            }

            internal static bool NotEmpty<T>(System.Collections.Generic.IEnumerable<T>? value, string name)
            {
                if (value is null)
                {
                    throw new System.ArgumentException("Value cannot be null or empty.", name);
                }

                using var enumerator = value.GetEnumerator();
                if (!enumerator.MoveNext())
                {
                    throw new System.ArgumentException("Value cannot be empty.", name);
                }

                return true;
            }

            internal static bool InRange(double value, double min, double max, string name)
            {
                if (value < min || value > max)
                {
                    throw new System.ArgumentOutOfRangeException(name, $"Value must be between {min} and {max}.");
                }

                return true;
            }

            internal static bool Matches(string? value, string pattern, string name)
            {
                if (value is null || !global::System.Text.RegularExpressions.Regex.IsMatch(value, pattern))
                {
                    throw new System.ArgumentException($"Value must match pattern '{pattern}'.", name);
                }

                return true;
            }
        }
        """;

    public static string Emit(GuardedTypeModel model)
    {
        var classDeclaration = $"{model.Accessibility} partial class {model.TypeName}{model.TypeParameters}{model.Constraints}";
        var validationChain = string.Join(" && ", model.Validations);

        if (string.IsNullOrEmpty(model.Namespace))
        {
            return $$"""
            // <auto-generated by Swevo.AutoGuard/>
            #nullable enable

            {{classDeclaration}}
            {
                private readonly bool _autoGuard = {{validationChain}};
            }
            """;
        }

        return $$"""
        // <auto-generated by Swevo.AutoGuard/>
        #nullable enable
        namespace {{model.Namespace}};

        {{classDeclaration}}
        {
            private readonly bool _autoGuard = {{validationChain}};
        }
        """;
    }
}
